# Generated by Django 5.1.4 on 2025-02-25 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 19, 12, 46, 855607)),
        ),
    ]
