# Generated by Django 5.1.4 on 2025-02-26 05:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectprogress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_progress_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_progress', to='main.project'),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='main.project')),
            ],
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_phase', to='main.projectphase'),
        ),
    ]
