# Generated by Django 5.1.4 on 2025-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectprogress_image_alter_project_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='about',
            field=models.TextField(default='Project Manager'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
