# Generated by Django 5.1.4 on 2025-03-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectmanager_about_projectmanager_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='about',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contractor',
            name='about',
            field=models.TextField(default='Project Contractor'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
