# Generated by Django 5.1.4 on 2025-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_projectphase_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
