# Generated by Django 5.1.4 on 2025-03-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projectprogress_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='project_progress_files/'),
        ),
    ]
